In [236]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
%matplotlib inline 
import matplotlib.pyplot as plt

In [237]:

cell_df = pd.read_csv('loan_train.csv',
                      )

print('Data downloaded and read into a dataframe!')




cell_df.head()
 



Data downloaded and read into a dataframe!


Unnamed: 0  Unnamed: 0.1 loan_status  Principal  terms effective_date  \
0           0             0     PAIDOFF       1000     30       9/8/2016   
1           2             2     PAIDOFF       1000     30       9/8/2016   
2           3             3     PAIDOFF       1000     15       9/8/2016   
3           4             4     PAIDOFF       1000     30       9/9/2016   
4           6             6     PAIDOFF       1000     30       9/9/2016   

    due_date  age             education  Gender  
0  10/7/2016   45  High School or Below    male  
1  10/7/2016   33              Bechalor  female  
2  9/22/2016   27               college    male  
3  10/8/2016   28               college  female  
4  10/8/2016   29               college    male

In [238]:
X = cell_df [['loan_status', 'education', 'Gender']].values




 


In [239]:
from sklearn import preprocessing
 
le_BP = preprocessing.LabelEncoder()
le_BP.fit([ 'PAIDOFF', 'COLLECTION'])
X[:,0] = le_BP.transform(X[:,0])  

le_BP = preprocessing.LabelEncoder()
le_BP.fit([ 'High School or Below', 'college' ,'Bechalor', 'Master or Above'])
X[:,1] = le_BP.transform(X[:,1])

le_BP = preprocessing.LabelEncoder()
le_BP.fit([ 'male', 'female' ])
X[:,2] = le_BP.transform(X[:,2])


 
cell_df.dtypes




X[0:10]

array([[1, 1, 1],
       [1, 0, 0],
       [1, 3, 1],
       [1, 3, 0],
       [1, 3, 1],
       [1, 3, 1],
       [1, 3, 1],
       [1, 3, 1],
       [1, 3, 1],
       [1, 1, 1]], dtype=object)

In [240]:
cell_df.head()

Unnamed: 0  Unnamed: 0.1 loan_status  Principal  terms effective_date  \
0           0             0     PAIDOFF       1000     30       9/8/2016   
1           2             2     PAIDOFF       1000     30       9/8/2016   
2           3             3     PAIDOFF       1000     15       9/8/2016   
3           4             4     PAIDOFF       1000     30       9/9/2016   
4           6             6     PAIDOFF       1000     30       9/9/2016   

    due_date  age             education  Gender  
0  10/7/2016   45  High School or Below    male  
1  10/7/2016   33              Bechalor  female  
2  9/22/2016   27               college    male  
3  10/8/2016   28               college  female  
4  10/8/2016   29               college    male

In [241]:
# creating a dict file  
status = {'PAIDOFF': 1,'COLLECTION': 0} 
  
    
# condition matches. 
cell_df.loan_status[cell_df.loan_status == 'PAIDOFF'] = 1
cell_df.loan_status[cell_df.loan_status == 'COLLECTION'] = 0

# condition matches. 
cell_df.Gender[cell_df.Gender == 'male'] = 0
cell_df.Gender[cell_df.Gender == 'female'] = 1

# condition matches. 
cell_df.education[cell_df.education == 'High School or Below'] = 0
cell_df.education[cell_df.education == 'college'] = 1
cell_df.education[cell_df.education == 'Bechalor'] = 2


# condition matches. 
cell_df.terms[cell_df.terms == 7] = 0
cell_df.terms[cell_df.terms == 15] = 1
cell_df.terms[cell_df.terms == 30] = 2



cell_df = cell_df[pd.to_numeric(cell_df['loan_status'], errors='coerce').notnull()]
cell_df['loan_status'] = cell_df['loan_status'].astype('int')
cell_df.dtypes

cell_df = cell_df[pd.to_numeric(cell_df['Gender'], errors='coerce').notnull()]
cell_df['Gender'] = cell_df['Gender'].astype('int')
cell_df.dtypes

cell_df = cell_df[pd.to_numeric(cell_df['education'], errors='coerce').notnull()]
cell_df['education'] = cell_df['education'].astype('int')
cell_df.dtypes


#cell_df.dtypes
print(cell_df) 



#cell_df['loan_status'] = cell_df['loan_status'].astype('int')
#y = np.asarray(cell_df['loan_status'])
#y [0:5]

/home/jupyterlab/conda/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
/home/jupyterlab/conda/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
/home/jupyterlab/conda/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
/home/jupyterlab/conda/lib/python3.6/site-packages/ipykerne

     Unnamed: 0  Unnamed: 0.1  loan_status  Principal  terms effective_date  \
0             0             0            1       1000      2       9/8/2016   
1             2             2            1       1000      2       9/8/2016   
2             3             3            1       1000      1       9/8/2016   
3             4             4            1       1000      2       9/9/2016   
4             6             6            1       1000      2       9/9/2016   
5             7             7            1       1000      2       9/9/2016   
6             8             8            1       1000      2       9/9/2016   
7             9             9            1        800      1      9/10/2016   
8            10            10            1        300      0      9/10/2016   
9            11            11            1       1000      1      9/10/2016   
10           12            12            1       1000      2      9/10/2016   
11           13            13            1        90

/home/jupyterlab/conda/lib/python3.6/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/home/jupyterlab/conda/lib/python3.6/site-packages/ipykernel_launcher.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/jupyterlab/conda/lib/python3.6/site-packages/ipykernel_launcher.py:21: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/jupyterlab/conda/lib/python3.6/site-packages/ipykernel_launcher.py:22: SettingWithCopyWarning

In [242]:
cell_df.columns
cell_df= cell_df.drop('effective_date', 1)
cell_df = test.drop('due_date',1)



In [243]:
X = cell_df[['Principal', 'terms','age', 'education', 'Gender']].values.astype(float)
X[0:5]

array([[1000.,    2.,   45.,    0.,    0.],
       [1000.,    2.,   33.,    2.,    1.],
       [1000.,    1.,   27.,    1.,    0.],
       [1000.,    2.,   28.,    1.,    1.],
       [1000.,    2.,   29.,    1.,    0.]])

In [244]:
#X = cell_df[cell_df['loan_status'] == 0][0:20].plot(kind='scatter', x='education', y='age', color='DarkBlue', label='malignant');
#cell_df[cell_df['loan_status'] == 1][0:20].plot(kind='scatter', x='education', y='age', color='DarkGreen', label='benign');
#plt.show()

In [245]:
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))
X[0:1000]

array([[ 0.51345952,  0.87869823,  2.37885075, -1.0048238 , -0.42199786],
       [ 0.51345952,  0.87869823,  0.35995768,  1.91213305,  2.36968028],
       [ 0.51345952, -0.85849827, -0.64948885,  0.45365463, -0.42199786],
       ...,
       [-1.31690394, -0.85849827,  1.36940421,  0.45365463, -0.42199786],
       [ 0.51345952,  0.87869823, -0.48124777,  0.45365463, -0.42199786],
       [ 0.51345952,  0.87869823, -0.81772994,  0.45365463, -0.42199786]])

In [246]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (275, 5) (275,)
Test set: (69, 5) (69,)


In [247]:
from sklearn.neighbors import KNeighborsClassifier

In [248]:
k = 4
#Train Model and Predict  
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
neigh

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=4, p=2,
           weights='uniform')

In [249]:
yhat = neigh.predict(X_test)
yhat[0:5]

array([1, 1, 1, 1, 0])

In [250]:
from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(y_train, neigh.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhat))

Train set Accuracy:  0.7490909090909091
Test set Accuracy:  0.6376811594202898
